name: Scrape
on:
  workflow_dispatch:
    inputs:
      resource:
        type: choice
        description: 'Key for the resource to scrape'
        options:
        - items
        - skill-icons

jobs:
  scrape:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Run scraper
      run: ./.github/scripts/scrape_wiki.sh ${{ github.event.inputs.resource }}

    - name: Read report
      id: read-report
      run: |
        delimiter="$(openssl rand -hex 8)"
        report=$(cat tmp/report.md)
        echo "report<<$delimiter" >> $GITHUB_OUTPUT
        echo "$report" >> $GITHUB_OUTPUT
        echo "$delimiter" >> $GITHUB_OUTPUT

    - name: Raise PR for any changes
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update ${{ github.event.inputs.resource }}
        branch: scraper/${{ github.event.inputs.resource }}
        delete-branch: true
        title: Update ${{ github.event.inputs.resource }}
        body: |
          Triggered by workflow [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ${{ steps.read-report.outputs.report }}
