name: Test
on:
  push:
  pull_request:

jobs:
  test:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: coursier/cache-action@v6

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.10.7

    - name: Run tests
      run: sbt test
