name: Update docs
on: push

jobs:
  update-docs:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Identify changes
      uses: dorny/paths-filter@v2
      id: identify-changes
      with:
        base: ${{ github.ref }}
        filters: |
          sources:
          - 'codec/js/src/main/**'
          - 'codec/shared/src/main/**'
          - 'common/js/src/main/**'
          - 'common/shared/src/main/**'
          - 'ui/src/main/**'
          - 'ui/package.json'
          - 'ui/package-lock.json'
          - 'ui/vite.config.js'
          - 'project/**'
          - 'build.sbt'

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: coursier/cache-action@v6
      if: steps.identify-changes.outputs.sources == 'true'

    - uses: actions/setup-java@v4
      if: steps.identify-changes.outputs.sources == 'true'
      with:
        distribution: temurin
        java-version: 17

    - uses: sbt/setup-sbt@v1
      if: steps.identify-changes.outputs.sources == 'true'
      with:
        sbt-runner-version: 1.10.7

    - name: Run tests
      if: steps.identify-changes.outputs.sources == 'true'
      run: sbt codecJS/test commonJS/test ui/test

    - name: Bundle javascript
      id: bundle-js
      if: steps.identify-changes.outputs.sources == 'true'
      run: |
        cd ui
        npm install
        npm run build

    - name: Sync docs
      if: ${{ (github.ref == 'refs/heads/master') && (steps.bundle-js.outcome == 'success') }}
      run: |
        ./.github/scripts/sync_docs.sh
        ./.github/scripts/commit_docs.sh
